// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2022-09-19 10:40:15.8938487 -0700 PDT m=+0.107223001
package cmd

const GITVERSION = `98e8529 Fix makefile version`
const SEMVER = "0.1.0"
const DEPENDENCIES = `module git.xx.network/elixxir/cli-client

go 1.17

require (
	github.com/awesome-gocui/gocui v1.1.0
	github.com/graph-gophers/graphql-go v1.4.0
	github.com/pkg/errors v0.9.1
	github.com/spf13/cobra v1.4.0
	github.com/spf13/jwalterweatherman v1.1.0
	github.com/spf13/pflag v1.0.5
	github.com/spf13/viper v1.11.0
	gitlab.com/elixxir/client v1.5.1-0.20220706193049-a0b718049663
	gitlab.com/elixxir/crypto v0.0.7-0.20220606201132-c370d5039cea
	gitlab.com/elixxir/primitives v0.0.3-0.20220606195757-40f7a589347f
	gitlab.com/xx_network/crypto v0.0.5-0.20220606200528-3f886fe49e81
	gitlab.com/xx_network/primitives v0.0.4-0.20220630163313-7890038258c6
)

require (
	github.com/badoux/checkmail v1.2.1 // indirect
	github.com/cloudflare/circl v1.1.0 // indirect
	github.com/elliotchance/orderedmap v1.4.0 // indirect
	github.com/fsnotify/fsnotify v1.5.1 // indirect
	github.com/gdamore/encoding v1.0.0 // indirect
	github.com/gdamore/tcell/v2 v2.4.0 // indirect
	github.com/golang-collections/collections v0.0.0-20130729185459-604e922904d3 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/hashicorp/hcl v1.0.0 // indirect
	github.com/inconshreveable/mousetrap v1.0.0 // indirect
	github.com/lucasb-eyer/go-colorful v1.0.3 // indirect
	github.com/magiconair/properties v1.8.6 // indirect
	github.com/mattn/go-runewidth v0.0.10 // indirect
	github.com/mitchellh/go-homedir v1.1.0 // indirect
	github.com/mitchellh/mapstructure v1.4.3 // indirect
	github.com/nfnt/resize v0.0.0-20180221191011-83c6a9932646 // indirect
	github.com/pelletier/go-toml v1.9.4 // indirect
	github.com/pelletier/go-toml/v2 v2.0.0-beta.8 // indirect
	github.com/rivo/uniseg v0.1.0 // indirect
	github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e // indirect
	github.com/spf13/afero v1.8.2 // indirect
	github.com/spf13/cast v1.4.1 // indirect
	github.com/subosito/gotenv v1.2.0 // indirect
	github.com/ttacon/builder v0.0.0-20170518171403-c099f663e1c2 // indirect
	github.com/ttacon/libphonenumber v1.2.1 // indirect
	github.com/tyler-smith/go-bip39 v1.1.0 // indirect
	gitlab.com/elixxir/bloomfilter v0.0.0-20211222005329-7d931ceead6f // indirect
	gitlab.com/elixxir/comms v0.0.4-0.20220603231314-e47e4af13326 // indirect
	gitlab.com/elixxir/ekv v0.1.7 // indirect
	gitlab.com/xx_network/comms v0.0.4-0.20220630163702-f3d372ef6acd // indirect
	gitlab.com/xx_network/ring v0.0.3-0.20220222211904-da613960ad93 // indirect
	golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4 // indirect
	golang.org/x/net v0.0.0-20220412020605-290c469a71a5 // indirect
	golang.org/x/sys v0.0.0-20220412211240-33da011f77ad // indirect
	golang.org/x/term v0.0.0-20210927222741-03fcf44c2211 // indirect
	golang.org/x/text v0.3.7 // indirect
	google.golang.org/genproto v0.0.0-20220407144326-9054f6ed7bac // indirect
	google.golang.org/grpc v1.45.0 // indirect
	google.golang.org/protobuf v1.28.0 // indirect
	gopkg.in/ini.v1 v1.66.4 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
)
`
